FROM docker.io/library/golang:latest AS build-env

WORKDIR /go/src

COPY todo-api.go /go/src

RUN go mod init github.com/naingyeminn/todolist/todo-api && \
    go mod tidy && \
    go build

FROM registry.access.redhat.com/ubi8-micro:latest
LABEL maintainer="Naing Ye Minn <naingyeminn@gmail.com>"

COPY --from=build-env /go/src/todo-api /app/todo-api

EXPOSE 8000

CMD ["/app/todo-api"]
